==========================================
SLURM_JOB_ID = 2365994
SLURM_NODELIST = gnode107
SLURM_JOB_GPUS = 2
==========================================

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


WARNING:root:Torch AMP is not available on this platform
config files: ['configs/Kinetics/MVITv2_S_gaze.yaml', 'TRAIN.BATCH_SIZE', '1']
Traceback (most recent call last):
  File "tools/run_net.py", line 51, in <module>
    main()
  File "tools/run_net.py", line 22, in main
    cfg = load_config(args, path_to_config)
  File "/scratch/mukil/SlowFast/slowfast/utils/parser.py", line 79, in load_config
    cfg.merge_from_file(path_to_config)
  File "/home2/shankar.gangisetty/miniconda3/envs/eye/lib/python3.8/site-packages/fvcore/common/config.py", line 119, in merge_from_file
    loaded_cfg = self.load_yaml_with_base(cfg_filename, allow_unsafe=allow_unsafe)
  File "/home2/shankar.gangisetty/miniconda3/envs/eye/lib/python3.8/site-packages/fvcore/common/config.py", line 59, in load_yaml_with_base
    with cls._open_cfg(filename) as f:
  File "/home2/shankar.gangisetty/miniconda3/envs/eye/lib/python3.8/site-packages/fvcore/common/config.py", line 40, in _open_cfg
    return g_pathmgr.open(filename, "r")
  File "/home2/shankar.gangisetty/miniconda3/envs/eye/lib/python3.8/site-packages/iopath/common/file_io.py", line 1012, in open
    bret = handler._open(path, mode, buffering=buffering, **kwargs)  # type: ignore
  File "/home2/shankar.gangisetty/miniconda3/envs/eye/lib/python3.8/site-packages/iopath/common/file_io.py", line 604, in _open
    return open(  # type: ignore
FileNotFoundError: [Errno 2] No such file or directory: 'configs/Kinetics/MVITv2_S_gaze.yaml'
